apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  source:
    # helm specific config
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/Gatefail/argocd-monitoring/master/src/overlays/local/values-local.yamlgi