apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  - description: Sync privileges for monitoring project
    name: monitoring-sync-ci-role
    policies:
    - p, proj:monitoring:monitoring-sync-ci-role, applications, sync, monitoring/monitoring-app,
      allow
  description: Monitoring project
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:Gatefail/argocd-monitoring.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    helm:
      releaseName: prometheus-operator
      valueFiles:
      - values-local.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
