apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
    - ./monitoring-app.yaml
    - ./monitoring-ns.yaml
    - ./monitoring-proj.yaml
    - ./alpha-metric-spammer-1-monitor.yaml
    - ./alpha-metric-spammer-2-monitor.yaml